export enum SupportedCurrencies {
  AustralianDollar = "AUD",
  USDollar = "USD",
  IndonesianRupiah = "IDR",
  JapaneseYen = "JPY",
  ThaiBaht = "THB",
  BritishPoundSterline = "GBP",
  Euro = "EUR",
  MalaysianRinggit = "MYR",
  IndianRupee = "INR",

  /*BrazilianReal = "BRL",
  BulgarianLev = "BGN",
  CanadianDollar = "CAD",
  ChineseYuanRenminbi = "CNY",
  CroatianKuna = "HRK",
  CzechKoruna = "CZK",
  DanishKrone = "DKK",
  HongKongDollar = "HKD",
  HungarianForint = "HUF",
  IcelandicKrona = "ISK",
  IndianRupee = "INR",
  IsraeliShekel = "ILS",
  MexicanPeso = "MXN",
  NewZealandDollar = "NZD",
  NorwegianKrone = "NOK",
  PhilippinePeso = "PHP",
  PolishZloty = "PLN",
  RomanianLeu = "RON",
  RussianRouble = "RUB",
  SingaporeDollar = "SGD",
  SouthAfricanRand = "ZAR",
  SouthKoreanWon = "KRW",
  SwedishKrona = "SEK",
  SwissFranc = "CHF",
  TurkishLira = "TRY",*/
}
